spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          # Указываем серверу искать конфиги в своих ресурсах, подставляя имя обратившегося клиента
          searchLocations:
            - classpath:config/telemetry/{application}
            - classpath:config/commerce/{application}
            - classpath:config/infra/{application}

server:
  port: 8888
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/