# Server
server.port=8080

# Kafka
spring.kafka.bootstrap-servers=localhost:9092
#spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
#spring.kafka.producer.value-serializer=io.confluent.kafka.serializers.KafkaAvroSerializer
#spring.kafka.producer.properties.schema.registry.url=http://localhost:8081

# Topics
kafka.topic.sensor-events=telemetry.sensors.v1
kafka.topic.hub-events=telemetry.hubs.v1

# Logging
logging.level.ru.yandex.practicum.telemetry.collector=DEBUG