# Server
server.port=8080

# gRPC Server
grpc.server.port=59091
grpc.server.security.enabled=false

# Spring
spring.application.name=Collector

# Kafka
spring.kafka.bootstrap-servers=localhost:9092

# Topics
kafka.topic.sensor-events=telemetry.sensors.v1
kafka.topic.hub-events=telemetry.hubs.v1

# Logging
logging.level.ru.yandex.practicum.telemetry.collector=DEBUG
logging.level.io.grpc=DEBUG
logging.level.net.devh.boot.grpc=DEBUG