spring.application.name=aggregator

spring.config.import=optional:configserver:http://localhost:8012

# ???? ?????? ???????????? ??????????, ?????????? ????? ?????? (?? ????? ??????????? ?? ?????? ????????)
spring.cloud.config.fail-fast=true

# ???????? ????????? ??????? ??????????? ??? ??????
spring.cloud.config.retry.use-random-policy=true
spring.cloud.config.retry.max-interval=6000