server:
  port: 8082

spring:
  application:
    name: Aggregator

sht:
  servers:
    bootstrap: localhost:9092
  aggregator:
    topics:
      sensors: telemetry.sensors.v1
      snapshots: telemetry.snapshots.v1